name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on Node

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - run: yarn lint
      - run: yarn build
